Currently, the system works this way: The default config "config.txt" holds all data which is necessary for the pack.
!!!DO NOT EDIT THIS FILE!!!

Now, you can create your own custom_config.txt and add the necessary data to the sections like in config.txt.
The values of custom_config.txt overrides the one in config.txt.

Example: When you want to increase e.g. the ZPM's maximum capacity, add the following to a blank file and call it user_config.txt:

# Starting the file...
# Anything which starts with a sharp is a comment and won't get recognized!

[zpm_mk3]
# We are changing the capacity! Horray for lifesupport cheating!
capacity = 10000000

# End of the file

Note: Every parameter is explained in config.txt!